language: python
sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install '.[dev]'
  - pip install coveralls

script:
  py.test -vv --cov=pydeps .

after_success:
  coveralls
